# Generated by Django 5.1.5 on 2025-02-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10),
        ),
    ]
